name: version
on: [push,workflow_dispatch]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest,ubuntu-latest]
        node_version: [14,15]
    steps:
       - name: checkout the code
         uses: actions/checkout@v3
       - name: download node
         uses: actions/setup-node@v3
       - name: execute
         run: node -v
