name: multi versions
on: [push,workflow_dispatch]

jobs:
  versions:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest,ubuntu-latest]
        node_version: [14,15]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: get nodejs
        uses: actions/setup-node@v3
        with:
         node-version: ${{ matrix.node_version }}
      - name: print
        run: node -v
  
