name: versions
on: [push,workflow_dispatch]
jobs:
  version-test:
     runs-on: ${{ matrix.os }}
     strategy:
        matrix:
          os: [macos-latest,ubuntu-latest,windows-latest]
          node_version: [14,15,16]
     steps:
        - name: checkout
          uses: actions/checkout@v3
        - name: download nodejs
          uses: actions/setup-node@v3
          with:
           node-version: ${{ matrix.node_version }}
        - name: run
          run:  node -v
          
           
        
